### PR TITLE
[OFFAPPS-540] Stop app from resetting everytime

### PR DESCRIPTION
**Pull request by pmgrove**
:v:

Stop app from resetting every time the app is initialised.

Thanks to @ocke for his help on this :smile_cat: 

/cc @zendesk/vegemite

### References
 - Jira link: https://zendesk.atlassian.net/browse/OFFAPPS-540

### Risks
 - None

### CODE REVIEW

**Comment by adammw** [comment]
:v: :+1:

**Comment by sandlerr** [comment]
that's deprecated, use [this](https://developer.zendesk.com/apps/docs/agent/events#app.created)?

**Comment by pmgrove** [comment]
Good call @sandlerr, will update. FYI @ocke

**Comment by pmgrove** [comment]
@sandlerr :haircut:

**Comment by danielbreves** [comment]
:+1:

**Comment by pmgrove** [comment]
@danielbreves, @sandlerr, @adammw :haircut: 

:+1:'s still stand?

**Comment by ocke** [comment]
:+1:

**Comment by adammw** [comment]
:+1:

**Comment by sandlerr** [comment]
:+1: (mine actually counts, unlike @ocke )

**Pull request merged**
