### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by adammw**
:koala:

/cc @zendesk/quokka

### Risks

### CODE REVIEW

**Comment by itirkarp** [comment]
Also add the other stuff that @sandlerr added, the samson link etc?

**Comment by adammw** [comment]
@sandlerr what did you add for the samson link?

**Comment by sandlerr** [comment]
copy from https://github.com/zendesklabs/chucknorris_app/pull/6

**Comment by sandlerr** [comment]
Just copy and paste the staging stuff at the bottom for prod

**Comment by maximeprades** [comment]
@sandlerr @adammw can we get this +1ed and merged please?

**Comment by sandlerr** [comment]
:+1:

**Pull request merged**
